services:
  api:
    build: .
    container_name: tuto_express
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run debug

  mongodb:
    image: mongo:latest
    container_name: mongodb_tuto_express
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
